server {
    listen ${PORT};
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    types {
        text/html                             html htm shtml;
        text/markdown                         md;
        text/plain                            txt py;
        application/json                      json;
        image/jpeg                            jpeg jpg;
        image/png                             png;
        image/svg+xml                         svg svgz;
        application/pdf                       pdf;
    }
}
